# Redirects
/fancyclean/privacy_policy          /app/privacy_policy.html
/fancycleanprime/privacy_policy     /app/privacy_policy.html
/emptyfolderclean/privacy_policy    /app/privacy_policy.html
/fancysecurity/privacy_policy       /app/privacy_policy.html
/fancycleanmini/privacy_policy      /app/privacy_policy.html
/fancyboost/privacy_policy          /app/privacy_policy.html
/fancyoptimizer/privacy_policy      /app/privacy_policy.html
/fancyapplock/privacy_policy        /app/privacy_policy.html
/fancybattery/privacy_policy        /app/privacy_policy.html
/app/privacy_policy                 /app/privacy_policy.html
