# Redirects
/fancyclean/privacy_policy          /fancyclean/privacy_policy.html
/fancycleanprime/privacy_policy     /fancycleanprime/privacy_policy.html
/emptyfolderclean/privacy_policy    /emptyfolderclean/privacy_policy.html
/fancysecurity/privacy_policy       /fancysecurity/privacy_policy.html
/fancycleanmini/privacy_policy      /fancycleanmini/privacy_policy.html
/fancyboost/privacy_policy          /fancyboost/privacy_policy.html
/fancyapplock/privacy_policy        /fancyapplock/privacy_policy.html
/app/privacy_policy                 /app/privacy_policy.html
