# Redirects
/fancyclean/privacy_policy       /fancyclean/privacy_policy.html
/emptyfolderclean/privacy_policy       /emptyfolderclean/privacy_policy.html
/fancysecurity/privacy_policy       /fancysecurity/privacy_policy.html
